from .auth import router as auth_router
from .users import router as users_router
from .menus import router as menus_router
from .fields import router as fields_router
from .ledger import router as ledger_router
from .archive import router as archive_router
from .files import router as files_router
from .warning import router as warning_router
from .fee import router as fee_router
from .dashboard import router as dashboard_router
from .system import router as system_router
